name: Cloud DevOps Multi-Stage Pipeline

on:
  push:
    branches: [ main ]

jobs:

  # -------------------------
  # STAGE 1 - BUILD & TEST
  # -------------------------
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic tests
        run: |
          echo "Running tests..."
          python -m compileall app/

  # -------------------------
  # STAGE 2 - DOCKER BUILD
  # -------------------------
  docker-build:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t flask-app:latest .

      - name: Save image locally
        run: |
          docker images

  # -------------------------
  # STAGE 3 - SECURITY SCAN
  # -------------------------
  security-scan:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'flask-app:latest'
          format: 'table'
          exit-code: '0'
          severity: 'HIGH,CRITICAL'

  # -------------------------
  # STAGE 4 - FINAL STATUS
  # -------------------------
  pipeline-status:
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - name: Success message
        run: echo "CI/CD Multi-Stage Pipeline completed successfully 🚀"